<html>
<body>
<div class="w3-container">
<form enctype="multipart/form-data" action="fileupload.php" method="post">
  <h4>Movie Title</h4><input type="text" name="name">
  <br/>
  <h4>Movie Description</h4><textarea name="description" rows="5" cols="50" wrap="physical">
  </textarea>
  <h4>Movie Emotion</h4>
  <input type="radio" name="mood" value="Agitated">Agitated<br>
  <input type="radio" name="mood" value="Calm">Calm<br>
  <input type="radio" name="mood" value="Happy">Happy<br>
  <input type="radio" name="mood" value="Sad">Sad<br>
  <input type="radio" name="mood" value="Tired">Tired<br>
  <input type="radio" name="mood" value="WideAwake">Wide Awake<br>
  <input type="radio" name="mood" value="Scared">Scared<br>
  <input type="radio" name="mood" value="Fearless">Fearless<br>
  <br/>
  Choose a file to upload: <input type="file" name="fileToUpload" id="fileToUpload" />
  <br/>
  <br/>
  <input type="submit" value="submit" name="submit" />
</form>
</div>

</body>
</html>
